### ISSUE TITLE
Error when loading site

### ISSUE THREAD

**Issue by AndrewMac** [ethercreative/notes#3]
Hello there, Ether Creative people

I just updated to the latest version of Notes, and immediately after my control panel stopped loading with the following error. I had to disable and uninstall Notes before I could get my CP back. 

This is the error 

> Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Stack trace follows:

yii\base\ErrorException: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /path/to/vendor/ether/notes/src/Field.php:143
Stack trace:
#0 /path/to/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8192, 'Unparenthesized...', '/Users/andrew/S...', 143)
#1 /path/to/vendor/composer/ClassLoader.php(444): craft\web\ErrorHandler->handleError(8192, 'Unparenthesized...', '/Users/andrew/S...', 143, Array)
#2 /path/to/vendor/composer/ClassLoader.php(444): include()
#3 /path/to/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/andrew/S...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('ether\\notes\\Fie...')
#5 /path/to/vendor/craftcms/cms/src/controllers/FieldsController.php(157): spl_autoload_call('ether\\notes\\Fie...')
#6 [internal function]: craft\controllers\FieldsController->actionEditField(NULL, Object(craft\fields\PlainText), NULL)
#7 /path/to/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /path/to/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /path/to/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-field', Array)
#10 /path/to/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#11 /path/to/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('fields/edit-fie...', Array)
#12 /path/to/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#13 /path/to/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#14 /path/to/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /path/to/web/index.php(21): yii\base\Application->run()
#16 {main}

**Comment by AndrewMac** [comment]
Hello? 
:-)
